### ISSUE TITLE
Exception in thread Thread-3: RuntimeError: cannot release un-acquired lock

### ISSUE THREAD

**Issue by codersneha3012** [NimzyMaina/flask_kafka#2]
I am facing this error again and again.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sneha/sneha/rps/flask_AI_AWS/model/flask_kafka/consumer.py", line 59, in _start
    for msg in self.consumer:
  File "/home/sneha/sneha/rps/venv/lib/python3.6/site-packages/kafka/consumer/group.py", line 1192, in __next__
    return self.next_v2()
  File "/home/sneha/sneha/rps/venv/lib/python3.6/site-packages/kafka/consumer/group.py", line 1200, in next_v2
    return next(self._iterator)
  File "/home/sneha/sneha/rps/venv/lib/python3.6/site-packages/kafka/consumer/group.py", line 1115, in _message_generator_v2
    record_map = self.poll(timeout_ms=timeout_ms, update_offsets=False)
  File "/home/sneha/sneha/rps/venv/lib/python3.6/site-packages/kafka/consumer/group.py", line 654, in poll
    records = self._poll_once(remaining, max_records, update_offsets=update_offsets)
  File "/home/sneha/sneha/rps/venv/lib/python3.6/site-packages/kafka/consumer/group.py", line 674, in _poll_once
    self._coordinator.poll()
  File "/home/sneha/sneha/rps/venv/lib/python3.6/site-packages/kafka/coordinator/consumer.py", line 286, in poll
    self.ensure_active_group()
  File "/home/sneha/sneha/rps/venv/lib/python3.6/site-packages/kafka/coordinator/base.py", line 427, in ensure_active_group
    time.sleep(self.config['retry_backoff_ms'] / 1000)
  File "/usr/lib/python3.6/threading.py", line 243, in __exit__
    return self._lock.__exit__(*args)
RuntimeError: cannot release un-acquired lock

Any suggestion on this?

**Comment by NimzyMaina** [comment]
A little more context would be nice. Some sample code of what you are doing or the scenario in which your project is running.
